### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Luvirini** [harvestingmoon/OBrainRot#3]
At end of generating autdio I get the following:

--------------------------
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
 > Processing time: 318.9844515323639
 > Real-time factor: 2.351609359716903
Traceback (most recent call last):
  File "C:\Users\UserName\brainrot\main.py", line 50, in <module>
    main(test_url, speaker_wav = "assets/default.mp3", video_path = 'assets/subway.mp4')
  File "C:\Users\UserName\brainrot\main.py", line 19, in main
    convert_audio('audio/output.wav',speech_final)
  File "C:\Users\UserName\brainrot\audio.py", line 30, in convert_audio
    subprocess.run(command, check=True)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
----------------------

I saw it reference the "assets/subway.mp4", that did not exist, so I tried copying the parkour_test.mp4 over to that name as test to that name but it did not make any change in behavior.

**Comment by harvestingmoon** [comment]
Hi, try to see if it now works :)
